course_name = "深度学习体系结构"
course_code = "COMP3043"
repo_type = "normal"
description = """
2019 级以前（2021 秋以前的秋季学期）作为计科的计算机系统方向的方向限选课。
2024 秋和 2025 夏作为跨专业选修课程开设，课程代码为 COMP3043C，内容不变。
"""

[lecturers]
[[lecturers.items]]
name = "曾国坤"
[[lecturers.items.reviews]]
content = "会提前发ppt。"
[[lecturers.items.reviews]]
content = "老师很好，不点名，讲课也不错"
author = { name = "离谱", link = "", date = "2026-04" }
[[sections]]
title = "关于实验"
[[sections.items]]
content = """
实验老师精心设计，生怕同学们做不出来。
因为要上板子，所以实验的时长都会偏长，也可能发生一些比较玄学的错误。
总体来说，实验不算太难。

"""